/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LinkedinTemplatesRouteImport } from './routes/linkedin-templates'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as EmailTemplatesRouteImport } from './routes/email-templates'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinTemplatesRoute = LinkedinTemplatesRouteImport.update({
  id: '/linkedin-templates',
  path: '/linkedin-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplatesRoute = EmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/applications': typeof ApplicationsRoute
  '/companies': typeof CompaniesRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/employees': typeof EmployeesRoute
  '/followups': typeof FollowupsRoute
  '/jobs': typeof JobsRoute
  '/linkedin-templates': typeof LinkedinTemplatesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/applications': typeof ApplicationsRoute
  '/companies': typeof CompaniesRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/employees': typeof EmployeesRoute
  '/followups': typeof FollowupsRoute
  '/jobs': typeof JobsRoute
  '/linkedin-templates': typeof LinkedinTemplatesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/applications': typeof ApplicationsRoute
  '/companies': typeof CompaniesRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/employees': typeof EmployeesRoute
  '/followups': typeof FollowupsRoute
  '/jobs': typeof JobsRoute
  '/linkedin-templates': typeof LinkedinTemplatesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/applications'
    | '/companies'
    | '/email-templates'
    | '/employees'
    | '/followups'
    | '/jobs'
    | '/linkedin-templates'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/applications'
    | '/companies'
    | '/email-templates'
    | '/employees'
    | '/followups'
    | '/jobs'
    | '/linkedin-templates'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/applications'
    | '/companies'
    | '/email-templates'
    | '/employees'
    | '/followups'
    | '/jobs'
    | '/linkedin-templates'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CompaniesRoute: typeof CompaniesRoute
  EmailTemplatesRoute: typeof EmailTemplatesRoute
  EmployeesRoute: typeof EmployeesRoute
  FollowupsRoute: typeof FollowupsRoute
  JobsRoute: typeof JobsRoute
  LinkedinTemplatesRoute: typeof LinkedinTemplatesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-templates': {
      id: '/linkedin-templates'
      path: '/linkedin-templates'
      fullPath: '/linkedin-templates'
      preLoaderRoute: typeof LinkedinTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates': {
      id: '/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof EmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  ApplicationsRoute: ApplicationsRoute,
  CompaniesRoute: CompaniesRoute,
  EmailTemplatesRoute: EmailTemplatesRoute,
  EmployeesRoute: EmployeesRoute,
  FollowupsRoute: FollowupsRoute,
  JobsRoute: JobsRoute,
  LinkedinTemplatesRoute: LinkedinTemplatesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
